# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _raspiCam
else:
    import _raspiCam

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


FLASH_OFF = _raspiCam.FLASH_OFF
MMAL_CAMERA_PREVIEW_PORT = _raspiCam.MMAL_CAMERA_PREVIEW_PORT
MMAL_CAMERA_VIDEO_PORT = _raspiCam.MMAL_CAMERA_VIDEO_PORT
MMAL_CAMERA_CAPTURE_PORT = _raspiCam.MMAL_CAMERA_CAPTURE_PORT

def initialize(format, flash, waitFlash, binning):
    return _raspiCam.initialize(format, flash, waitFlash, binning)

def getImage(seq, shutter, delay):
    return _raspiCam.getImage(seq, shutter, delay)

def getImageBuffer(seq, len, shutter):
    return _raspiCam.getImageBuffer(seq, len, shutter)

def finalize():
    return _raspiCam.finalize()

def setFlash(flash):
    return _raspiCam.setFlash(flash)
FRAME_NEXT_SINGLE = _raspiCam.FRAME_NEXT_SINGLE
FRAME_NEXT_TIMELAPSE = _raspiCam.FRAME_NEXT_TIMELAPSE
FRAME_NEXT_KEYPRESS = _raspiCam.FRAME_NEXT_KEYPRESS
FRAME_NEXT_FOREVER = _raspiCam.FRAME_NEXT_FOREVER
FRAME_NEXT_GPIO = _raspiCam.FRAME_NEXT_GPIO
FRAME_NEXT_SIGNAL = _raspiCam.FRAME_NEXT_SIGNAL
FRAME_NEXT_IMMEDIATELY = _raspiCam.FRAME_NEXT_IMMEDIATELY
FORMAT_RAW = _raspiCam.FORMAT_RAW
FORMAT_RGB = _raspiCam.FORMAT_RGB
FORMAT_YUV_Y = _raspiCam.FORMAT_YUV_Y


